


<h1><?php echo $this->current_date; ?></h1>
<h2>&pound;<?php echo $this->statement->getBalance(); ?></h2>
        

<table border="2" width="100%">

    <tr>
        <th>Date</th>
        <th>Total Amount</th>
        <th>Total Transactions</th>
    </tr>
    
    <?php foreach ($this->statement  AS $activity) : ?>

    <tr>
        <td><?php echo $activity->date; ?></td>
        <td><?php echo $activity->balance; ?></td>
        <td>
            <?php if (count($activity->transactions)>0) :  ?>
                <table border="0" cellpadding="5">
                    <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Tags</th>
                        <th>Categories</th>
                    </tr>
                <?php  foreach ($activity->transactions AS $transaction) : ?>
                    <tr>
                        <td><?php echo "<a href='/transaction/edit/{$transaction->id}/' title='Edit {$transaction->name}'>{$transaction->name}</a><br />"; ?></td>
                        <td><?php echo "<a href='/transaction/edit/{$transaction->id}/' title='Edit {$transaction->name}'>&pound;{$transaction->amount}</a><br />"; ?></td>
                        <td>
                            <?php
                             if (count($transaction->tags)>0){
                                foreach ($transaction->tags AS $tag){
                                    echo "<a href='/tag/edit/{$tag->tag_id}' title='Edit {$tag->tag_name}'>{$tag->tag_name}</a><br />";
                                }
                            }?>
                        </td>
                        <td>
                            <?php
                            if (count($transaction->categories)>0){

                                foreach ($transaction->categories AS $category){
                                    echo "<a href='/category/edit/{$category->category_id}' title='Edit {$category->category_name}'>{$category->category_name}</a><br />";
                                }

                            }?>
                        </td>
                    </tr>
            <?php endforeach; ?>
            </table>
            
            <?php endif; ?>

    </tr>
    <?php endforeach; ?>
                
</table>