

<ul>
    <?php
    foreach($this->tags AS $tag){
        echo "<li><a href=''>{$tag->tag_name}</a></li>";
    }
    ?>
</ul>

<?php foreach ($this->transactions AS $transaction){
    
    echo "<hr><p>Id:{$transaction->id} Active:{$transaction->active} Name:{$transaction->name} Amount:{$transaction->amount}</p>";
    foreach ($transaction->tags AS $tag){
        echo "<li>{$tag->tag_name}</li>";
    }
    foreach ($transaction->categories AS $category){
        echo "<li>{$category->category_name}</li>";
    }
    
} ?>
